### ISSUE TITLE
Landowner report, disordered depth profile

### ISSUE THREAD

**Issue by kruehling** [USEPA/NARS-Data-Extraction-Tool#3]
Hello, 

I work for Wyoming DEQ and took part in the 2022 NLA surveys, when creating our landowner reports from data collected this summer we found that the depth profile was often not in a easily understandable order. I have attached an screen shot of the profile section of a report. Please let me know if there are any easy solutions to this problem on my end. 

Thanks
Kelsey Ruehling
![image](https://user-images.githubusercontent.com/64177356/198341922-90260866-78ed-485e-af87-636b56ace011.png)

**Comment by kblocksom** [comment]
Thanks for that feedback. It looks like the depth column is being treated as a character variable instead of numeric. I will try to correct the code now.

**Comment by kblocksom** [comment]
I've updated code that should now order by depth instead of line number.
